# Generated by Django 6.0.6 on 2026-06-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeExercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
            ],
            options={
                'verbose_name': "Année d'exercice",
                'verbose_name_plural': "Années d'exercice",
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Beneficiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Bénéficiaire')),
                ('responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ComptePrincipale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_compte', models.IntegerField(unique=True, verbose_name='N° Compte')),
                ('famille', models.CharField(max_length=200, verbose_name='Famille')),
            ],
            options={
                'verbose_name': 'Compte principal',
                'verbose_name_plural': 'Comptes principaux',
                'ordering': ['num_compte'],
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code dépôt')),
            ],
            options={
                'verbose_name': 'Dépôt',
                'verbose_name_plural': 'Dépôts',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Fournisseur')),
                ('adresse', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('fax', models.CharField(blank=True, max_length=30, verbose_name='Fax')),
                ('code_postal', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('fonction', models.CharField(blank=True, max_length=100, verbose_name='Fonction')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('num_bon', models.IntegerField(default=0, verbose_name='N° Bon')),
                ('type_entree', models.CharField(max_length=100, verbose_name='Type opération')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('nomenclature', models.CharField(max_length=30, verbose_name='Nomenclature')),
                ('specification', models.CharField(blank=True, max_length=300, verbose_name='Spécification')),
                ('qte', models.IntegerField(default=0, verbose_name='Quantité')),
                ('unite', models.CharField(blank=True, max_length=50, verbose_name='Unité')),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TTC')),
                ('beneficiaire', models.CharField(blank=True, max_length=200, verbose_name='Bénéficiaire')),
                ('annee_exercice', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('depot', models.CharField(blank=True, max_length=50, verbose_name='Dépôt')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('existant', models.IntegerField(default=0, verbose_name='Existant')),
                ('entree_periode', models.IntegerField(default=0, verbose_name='Entrée')),
                ('sortie_periode', models.IntegerField(default=0, verbose_name='Sortie')),
                ('existant_fin_periode', models.IntegerField(default=0, verbose_name='Existant fin période')),
                ('montant_existant', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant existant')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journal des opérations',
                'ordering': ['-date_creation', '-num_bon'],
            },
        ),
        migrations.CreateModel(
            name='MembreCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('qualite', models.CharField(max_length=200, verbose_name='Qualité')),
            ],
            options={
                'verbose_name': 'Membre de commission',
                'verbose_name_plural': 'Membres de commission',
            },
        ),
        migrations.CreateModel(
            name='MembreCommissionReforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('qualite', models.CharField(max_length=200, verbose_name='Qualité')),
            ],
            options={
                'verbose_name': 'Membre de commission de réforme',
                'verbose_name_plural': 'Membres de commission de réforme',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100, verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='ProfilCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualite', models.CharField(max_length=200, verbose_name='Qualité')),
            ],
            options={
                'verbose_name': 'Profil commission',
                'verbose_name_plural': 'Profils commission',
            },
        ),
        migrations.CreateModel(
            name='SocieteGCS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom société')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('adresse', models.CharField(blank=True, max_length=300, verbose_name='Adresse')),
                ('fax', models.CharField(blank=True, max_length=30, verbose_name='Fax')),
                ('ministere', models.CharField(blank=True, max_length=200, verbose_name='Ministère')),
                ('administrateur', models.CharField(blank=True, max_length=100, verbose_name='Administrateur')),
                ('comptable', models.CharField(blank=True, max_length=100, verbose_name='Comptable')),
                ('receptionnaire', models.CharField(blank=True, max_length=100, verbose_name='Réceptionnaire')),
                ('responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Société GCS',
            },
        ),
        migrations.CreateModel(
            name='TypeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100, verbose_name="Type d'opération")),
            ],
            options={
                'verbose_name': "Type d'opération",
                'verbose_name_plural': "Types d'opération",
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50, verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Unité',
                'verbose_name_plural': 'Unités',
            },
        ),
        migrations.CreateModel(
            name='BonSortieProvisoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon', models.IntegerField(verbose_name='N° Bon')),
                ('date_retour_prevue', models.DateField(blank=True, null=True, verbose_name='Date retour prévue')),
                ('annee_creation', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.beneficiaire', verbose_name='Bénéficiaire')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Bon de sortie provisoire',
                'verbose_name_plural': 'Bons de sortie provisoire',
                'ordering': ['-annee_creation', '-num_bon'],
            },
        ),
        migrations.CreateModel(
            name='BonSortieDefinitiveG1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon', models.IntegerField(verbose_name='N° Bon')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('annee_exercice', models.IntegerField(blank=True, null=True, verbose_name="Année d'exercice")),
                ('type_sortie', models.CharField(blank=True, max_length=100, verbose_name='Type de sortie')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.beneficiaire', verbose_name='Bénéficiaire')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Bon de sortie définitive G1',
                'verbose_name_plural': 'Bons de sortie définitive G1 (Réformes)',
                'ordering': ['-date_creation', '-num_bon'],
            },
        ),
        migrations.CreateModel(
            name='BonSortieDefinitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon', models.IntegerField(verbose_name='N° Bon')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('annee_exercice', models.IntegerField(blank=True, null=True, verbose_name="Année d'exercice")),
                ('type_sortie', models.CharField(blank=True, max_length=100, verbose_name='Type de sortie')),
                ('confirme', models.BooleanField(default=False, verbose_name='Confirmé')),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.beneficiaire', verbose_name='Bénéficiaire')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Bon de sortie définitive',
                'verbose_name_plural': 'Bons de sortie définitive',
                'ordering': ['-date_creation', '-num_bon'],
            },
        ),
        migrations.CreateModel(
            name='BonRetourSortieProvisoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon', models.IntegerField(verbose_name='N° Bon')),
                ('date_retour', models.DateField(blank=True, null=True, verbose_name='Date de retour')),
                ('annee_creation', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.beneficiaire', verbose_name='Bénéficiaire')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Bon de retour sortie provisoire',
                'verbose_name_plural': 'Bons de retour sortie provisoire',
                'ordering': ['-annee_creation', '-num_bon'],
            },
        ),
        migrations.CreateModel(
            name='BonRetourAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon', models.IntegerField(verbose_name='N° Bon')),
                ('date_retour', models.DateField(blank=True, null=True, verbose_name='Date de retour')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.beneficiaire', verbose_name='Bénéficiaire')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': "Bon de retour d'affectation",
                'verbose_name_plural': "Bons de retour d'affectation",
                'ordering': ['-date_creation', '-num_bon'],
            },
        ),
        migrations.CreateModel(
            name='BonEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon', models.IntegerField(verbose_name='N° Bon')),
                ('date_creation', models.DateField(verbose_name='Date de création')),
                ('references_pieces', models.CharField(blank=True, max_length=200, verbose_name='Références pièces')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('num_bon_engagement', models.IntegerField(default=0, verbose_name="N° Bon d'engagement")),
                ('num_bon_commande', models.IntegerField(default=0, verbose_name='N° Bon de commande')),
                ('chapitre', models.CharField(blank=True, max_length=100, verbose_name='Chapitre')),
                ('annee_exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.anneeexercice', verbose_name="Année d'exercice")),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.depot', verbose_name='Dépôt')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.fournisseur', verbose_name='Fournisseur')),
                ('type_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.typeoperation', verbose_name="Type d'entrée")),
            ],
            options={
                'verbose_name': "Bon d'entrée",
                'verbose_name_plural': "Bons d'entrée",
                'ordering': ['-date_creation', '-num_bon'],
            },
        ),
        migrations.CreateModel(
            name='BonAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon', models.IntegerField(verbose_name='N° Bon')),
                ('date_affectation', models.DateField(blank=True, null=True, verbose_name="Date d'affectation")),
                ('annee_creation', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('confirmation', models.BooleanField(default=False, verbose_name='Confirmé')),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.beneficiaire', verbose_name='Bénéficiaire')),
                ('depot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': "Bon d'affectation",
                'verbose_name_plural': "Bons d'affectation",
                'ordering': ['-date_affectation', '-num_bon'],
            },
        ),
        migrations.CreateModel(
            name='MatieresDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sous_compte', models.IntegerField(verbose_name='N° Sous-compte')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matieres.depot', verbose_name='Dépôt')),
            ],
            options={
                'verbose_name': 'Matières/Dépôt',
                'verbose_name_plural': 'Matières/Dépôts',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=30, unique=True, verbose_name='Nomenclature')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('stock_global', models.IntegerField(default=0, verbose_name='Stock global')),
                ('qte_affectation', models.IntegerField(default=0, verbose_name='Qté affectée')),
                ('qte_sd', models.IntegerField(default=0, verbose_name='Qté sortie définitive')),
                ('entree', models.IntegerField(default=0, verbose_name='Entrée')),
                ('specification', models.CharField(blank=True, max_length=300, verbose_name='Spécification')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('qte_sp', models.IntegerField(default=0, verbose_name='Qté sortie provisoire')),
                ('compte_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='matieres.compteprincipale', verbose_name='Compte principal')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nomenclature'],
            },
        ),
        migrations.CreateModel(
            name='BalancePeriodique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=30, verbose_name='Nomenclature')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('unite', models.CharField(max_length=50, verbose_name='Unité')),
                ('existant_dp', models.IntegerField(default=0, verbose_name='Existant début période')),
                ('entree_periode', models.IntegerField(default=0, verbose_name='Entrée période')),
                ('total_entree', models.IntegerField(default=0, verbose_name='Total entrée')),
                ('sortie_periode', models.IntegerField(default=0, verbose_name='Sortie période')),
                ('existant_fin_periode', models.IntegerField(default=0, verbose_name='Existant fin période')),
                ('prix_unitaire_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix unitaire HT')),
                ('montant_existant', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant existant')),
                ('annee_exercice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.anneeexercice', verbose_name="Année d'exercice")),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Balance périodique',
                'verbose_name_plural': 'Balances périodiques',
            },
        ),
        migrations.CreateModel(
            name='SousCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sous_compte', models.FloatField(verbose_name='N° Sous-compte')),
                ('famille_sc', models.CharField(max_length=200, verbose_name='Famille sous-compte')),
                ('compte_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sous_comptes', to='matieres.compteprincipale', verbose_name='Compte principal')),
            ],
            options={
                'verbose_name': 'Sous-compte',
                'verbose_name_plural': 'Sous-comptes',
                'ordering': ['num_sous_compte'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='sous_compte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='matieres.souscompte', verbose_name='Sous-compte'),
        ),
        migrations.CreateModel(
            name='StockDepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.CharField(max_length=30, verbose_name='Nomenclature')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('qte_stock', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matieres.depot', verbose_name='Dépôt')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='matieres.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Stock Dépôt',
                'verbose_name_plural': 'Stocks Dépôts',
                'ordering': ['depot', 'nomenclature'],
            },
        ),
        migrations.AddField(
            model_name='produit',
            name='unite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.unite', verbose_name='Unité'),
        ),
        migrations.CreateModel(
            name='DetailBonSortieProvisoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('nomenclature', models.CharField(max_length=30, verbose_name='Nomenclature')),
                ('specification', models.CharField(blank=True, max_length=300, verbose_name='Spécification')),
                ('qte', models.IntegerField(default=0, verbose_name='Quantité')),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TTC')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('bon_sortie_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='matieres.bonsortieprovisoire')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.produit', verbose_name='Produit')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Détail sortie provisoire',
            },
        ),
        migrations.CreateModel(
            name='DetailBonSortieDefinitiveG1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('nomenclature', models.CharField(max_length=30, verbose_name='Nomenclature')),
                ('specification', models.CharField(blank=True, max_length=300, verbose_name='Spécification')),
                ('qte', models.IntegerField(default=0, verbose_name='Quantité')),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TTC')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('bon_sortie_g1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='matieres.bonsortiedefinitiveg1')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.produit', verbose_name='Produit')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Détail sortie définitive G1',
            },
        ),
        migrations.CreateModel(
            name='DetailBonSortieDefinitive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('nomenclature', models.CharField(max_length=30, verbose_name='Nomenclature')),
                ('specification', models.CharField(blank=True, max_length=300, verbose_name='Spécification')),
                ('qte', models.IntegerField(default=0, verbose_name='Quantité')),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TTC')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('bon_sortie_d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='matieres.bonsortiedefinitive')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.produit', verbose_name='Produit')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Détail sortie définitive',
            },
        ),
        migrations.CreateModel(
            name='DetailBonRetourSortieProvisoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('nomenclature', models.CharField(max_length=30, verbose_name='Nomenclature')),
                ('specification', models.CharField(blank=True, max_length=300, verbose_name='Spécification')),
                ('qte', models.IntegerField(default=0, verbose_name='Quantité')),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TTC')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('bon_retour_sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='matieres.bonretoursortieprovisoire')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.produit', verbose_name='Produit')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Détail retour sortie provisoire',
            },
        ),
        migrations.CreateModel(
            name='DetailBonRetourAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('nomenclature', models.CharField(max_length=30, verbose_name='Nomenclature')),
                ('specification', models.CharField(blank=True, max_length=300, verbose_name='Spécification')),
                ('qte', models.IntegerField(default=0, verbose_name='Quantité')),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TTC')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('bon_retour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='matieres.bonretouraffectation')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.produit', verbose_name='Produit')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': "Détail retour d'affectation",
            },
        ),
        migrations.CreateModel(
            name='DetailBonEntree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('nomenclature', models.CharField(max_length=30, verbose_name='Nomenclature')),
                ('specification', models.CharField(blank=True, max_length=300, verbose_name='Spécification')),
                ('qte', models.IntegerField(default=0, verbose_name='Quantité')),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TTC')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('bon_entree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='matieres.bonentree')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.produit', verbose_name='Produit')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': "Détail bon d'entrée",
                'verbose_name_plural': "Détails bons d'entrée",
            },
        ),
        migrations.CreateModel(
            name='DetailBonAffectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('nomenclature', models.CharField(max_length=30, verbose_name='Nomenclature')),
                ('specification', models.CharField(blank=True, max_length=300, verbose_name='Spécification')),
                ('qte', models.IntegerField(default=0, verbose_name='Quantité')),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TTC')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('bon_affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='matieres.bonaffectation')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.produit', verbose_name='Produit')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': "Détail bon d'affectation",
            },
        ),
    ]
