# Generated by Django 6.0.6 on 2026-06-29 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonaffectation',
            name='confirmation',
        ),
        migrations.RemoveField(
            model_name='bonsortiedefinitive',
            name='confirme',
        ),
        migrations.AddField(
            model_name='bonaffectation',
            name='depot_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_destination', to='matieres.depot', verbose_name='Dépôt destination'),
        ),
        migrations.AddField(
            model_name='bonaffectation',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observation'),
        ),
        migrations.AddField(
            model_name='bonaffectation',
            name='valide',
            field=models.BooleanField(default=False, verbose_name='Validé'),
        ),
        migrations.AddField(
            model_name='bonretouraffectation',
            name='depot_destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retours_affectation_destination', to='matieres.depot', verbose_name='Dépôt destination'),
        ),
        migrations.AddField(
            model_name='bonretouraffectation',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observation'),
        ),
        migrations.AddField(
            model_name='bonretouraffectation',
            name='valide',
            field=models.BooleanField(default=False, verbose_name='Validé'),
        ),
        migrations.AddField(
            model_name='bonsortiedefinitive',
            name='groupe',
            field=models.CharField(choices=[('1', 'Groupe 1 (1x.xx.xx)'), ('2', 'Groupe 2 (2x.xx.xx)')], default='1', max_length=1, verbose_name='Groupe de matières'),
        ),
        migrations.AddField(
            model_name='bonsortiedefinitive',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observation'),
        ),
        migrations.AddField(
            model_name='bonsortiedefinitive',
            name='valide',
            field=models.BooleanField(default=False, verbose_name='Validé'),
        ),
        migrations.AlterField(
            model_name='bonaffectation',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.depot', verbose_name='Dépôt source'),
        ),
        migrations.AlterField(
            model_name='bonretouraffectation',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.depot', verbose_name='Dépôt source'),
        ),
    ]
