# Generated by Django 6.0.6 on 2026-06-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0002_normalise_bons_champs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonretoursortieprovisoire',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observation'),
        ),
        migrations.AddField(
            model_name='bonsortieprovisoire',
            name='date_sortie',
            field=models.DateField(blank=True, null=True, verbose_name='Date de sortie'),
        ),
        migrations.AddField(
            model_name='bonsortieprovisoire',
            name='observation',
            field=models.TextField(blank=True, verbose_name='Observation'),
        ),
    ]
