# Generated by Django 6.0.6 on 2026-06-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0003_bsp_brsp_champs'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='date_affectation',
            field=models.DateField(blank=True, null=True, verbose_name='Date affectation'),
        ),
        migrations.AddField(
            model_name='journal',
            name='date_retour',
            field=models.DateField(blank=True, null=True, verbose_name='Date retour réelle'),
        ),
        migrations.AddField(
            model_name='journal',
            name='date_retour_affectation',
            field=models.DateField(blank=True, null=True, verbose_name='Date retour BA'),
        ),
        migrations.AddField(
            model_name='journal',
            name='groupe',
            field=models.CharField(blank=True, max_length=10, verbose_name='Groupe'),
        ),
        migrations.AddField(
            model_name='journal',
            name='num_bon_sortie',
            field=models.IntegerField(default=0, verbose_name='N° Bon sortie déf.'),
        ),
        migrations.AddField(
            model_name='journal',
            name='qte_affectation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qté affectation'),
        ),
        migrations.AddField(
            model_name='journal',
            name='qte_rba',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qté retour BA'),
        ),
        migrations.AddField(
            model_name='journal',
            name='qte_sd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qté sortie déf.'),
        ),
        migrations.AddField(
            model_name='journal',
            name='qte_sp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qté sortie prov.'),
        ),
        migrations.AddField(
            model_name='journal',
            name='qte_stock_partielle',
            field=models.CharField(blank=True, max_length=50, verbose_name='Stock dépôt'),
        ),
        migrations.AddField(
            model_name='journal',
            name='total_entree',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total entrée'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Date création'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='entree_periode',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Entrée période'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='existant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Existant'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='existant_fin_periode',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Existant fin période'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='nomenclature',
            field=models.CharField(max_length=50, verbose_name='Nomenclature'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='qte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='sortie_periode',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Sortie période'),
        ),
    ]
