# Generated by Django 6.0.6 on 2026-06-30 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0004_journal_rubriques_completes'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbonaffectation',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details_ba', to='matieres.journal', verbose_name='Entrée journal'),
        ),
        migrations.AlterField(
            model_name='detailbonaffectation',
            name='nomenclature',
            field=models.CharField(max_length=50, verbose_name='Nomenclature'),
        ),
        migrations.AlterField(
            model_name='detailbonaffectation',
            name='observation',
            field=models.CharField(blank=True, max_length=300, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='detailbonaffectation',
            name='prix_ht',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix Unitaire HT'),
        ),
        migrations.AlterField(
            model_name='detailbonaffectation',
            name='prix_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix Unitaire TTC'),
        ),
        migrations.AlterField(
            model_name='detailbonaffectation',
            name='qte',
            field=models.IntegerField(default=0, verbose_name='QTé BA'),
        ),
    ]
