# Generated by Django 6.0.6 on 2026-07-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0005_detail_ba_windev_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonentree',
            name='num_pvc',
            field=models.CharField(blank=True, max_length=50, verbose_name='N° PVC'),
        ),
    ]
