# Generated by Django 6.0.6 on 2026-07-01 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0006_bonentree_add_num_pvc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Bureau',
                'verbose_name_plural': 'Bureaux',
                'ordering': ['service__code', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('responsable', models.CharField(blank=True, max_length=200, verbose_name='Responsable')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='journal',
            name='bureau',
            field=models.CharField(blank=True, max_length=200, verbose_name='Bureau'),
        ),
        migrations.AddField(
            model_name='journal',
            name='service',
            field=models.CharField(blank=True, max_length=200, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='beneficiaire',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='beneficiaire',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaires', to='matieres.bureau', verbose_name='Bureau'),
        ),
        migrations.AddField(
            model_name='bureau',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='matieres.service', verbose_name='Service'),
        ),
        migrations.AlterUniqueTogether(
            name='bureau',
            unique_together={('service', 'code')},
        ),
    ]
