# Generated by Django 6.0.6 on 2026-07-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0007_service_bureau_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortiedefinitive',
            name='chapitre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chapitre'),
        ),
    ]
