# Generated by Django 6.0.6 on 2026-07-07 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0008_bonsortiedefinitive_chapitre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonaffectation',
            name='beneficiaire',
        ),
        migrations.RemoveField(
            model_name='bonretouraffectation',
            name='beneficiaire',
        ),
        migrations.RemoveField(
            model_name='bonretoursortieprovisoire',
            name='beneficiaire',
        ),
        migrations.RemoveField(
            model_name='bonsortiedefinitive',
            name='beneficiaire',
        ),
        migrations.RemoveField(
            model_name='bonsortiedefinitiveg1',
            name='beneficiaire',
        ),
        migrations.RemoveField(
            model_name='bonsortieprovisoire',
            name='beneficiaire',
        ),
        migrations.AddField(
            model_name='bonaffectation',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.bureau', verbose_name='Bureau'),
        ),
        migrations.AddField(
            model_name='bonaffectation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='bonretouraffectation',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.bureau', verbose_name='Bureau'),
        ),
        migrations.AddField(
            model_name='bonretouraffectation',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='bonretoursortieprovisoire',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.bureau', verbose_name='Bureau'),
        ),
        migrations.AddField(
            model_name='bonretoursortieprovisoire',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='bonsortiedefinitive',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.bureau', verbose_name='Bureau'),
        ),
        migrations.AddField(
            model_name='bonsortiedefinitive',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='bonsortiedefinitiveg1',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.bureau', verbose_name='Bureau'),
        ),
        migrations.AddField(
            model_name='bonsortiedefinitiveg1',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.service', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='bonsortieprovisoire',
            name='bureau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.bureau', verbose_name='Bureau'),
        ),
        migrations.AddField(
            model_name='bonsortieprovisoire',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.service', verbose_name='Service'),
        ),
    ]
