# Generated by Django 6.0.6 on 2026-07-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0009_remove_bonaffectation_beneficiaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortieprovisoire',
            name='chapitre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chapitre'),
        ),
    ]
