# Generated by Django 6.0.6 on 2026-07-09 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0010_bonsortieprovisoire_chapitre'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon', models.IntegerField(verbose_name='N° Bon')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Date de création')),
                ('annee_exercice', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('bureau_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_destination', to='matieres.bureau', verbose_name='Bureau destination')),
                ('bureau_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_origine', to='matieres.bureau', verbose_name='Bureau origine')),
                ('service_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_destination', to='matieres.service', verbose_name='Service destination')),
                ('service_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutations_origine', to='matieres.service', verbose_name='Service origine')),
            ],
            options={
                'verbose_name': 'Bordereau de mutation',
                'verbose_name_plural': 'Bordereaux de mutation',
                'ordering': ['-date_creation', '-num_bon'],
            },
        ),
        migrations.CreateModel(
            name='DetailBonMutation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('nomenclature', models.CharField(max_length=30, verbose_name='Nomenclature')),
                ('code_immatriculation', models.CharField(blank=True, max_length=100, verbose_name="Code d'immatriculation")),
                ('qte', models.IntegerField(default=0, verbose_name='Quantité')),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TTC')),
                ('observation', models.CharField(blank=True, max_length=300, verbose_name='Observation')),
                ('bon_mutation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='matieres.bonmutation')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.produit', verbose_name='Produit')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Détail mutation',
            },
        ),
    ]
