# Generated by Django 6.0.6 on 2026-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0011_bonmutation_detailbonmutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailbonaffectation',
            name='code_immatriculation',
            field=models.CharField(blank=True, max_length=100, verbose_name="Code d'immatriculation"),
        ),
    ]
