# Generated by Django 6.0.6 on 2026-07-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0013_detailbonretoursortieprov_code_immatriculation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonsortiedefinitiveg1',
            options={'ordering': ['-date_creation', '-num_bon'], 'verbose_name': 'PV de réforme des matières (G1)', 'verbose_name_plural': 'PV de réforme des matières (G1)'},
        ),
        migrations.AlterModelOptions(
            name='detailbonsortiedefinitiveg1',
            options={'verbose_name': 'Détail PV de réforme (G1)'},
        ),
        migrations.RemoveField(
            model_name='bonsortiedefinitiveg1',
            name='type_sortie',
        ),
        migrations.RemoveField(
            model_name='detailbonsortiedefinitiveg1',
            name='montant_ttc',
        ),
        migrations.RemoveField(
            model_name='detailbonsortiedefinitiveg1',
            name='prix_ht',
        ),
        migrations.RemoveField(
            model_name='detailbonsortiedefinitiveg1',
            name='prix_ttc',
        ),
        migrations.RemoveField(
            model_name='detailbonsortiedefinitiveg1',
            name='qte',
        ),
        migrations.AddField(
            model_name='bonsortiedefinitiveg1',
            name='autorite_approbation',
            field=models.CharField(blank=True, max_length=300, verbose_name="Approbation de l'Autorité compétente"),
        ),
        migrations.AddField(
            model_name='bonsortiedefinitiveg1',
            name='chapitre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chapitre'),
        ),
        migrations.AddField(
            model_name='bonsortiedefinitiveg1',
            name='membres_commission',
            field=models.TextField(blank=True, verbose_name='Membres de la commission de réforme'),
        ),
        migrations.AddField(
            model_name='bonsortiedefinitiveg1',
            name='observations_commission',
            field=models.TextField(blank=True, verbose_name='Autres observations de la commission'),
        ),
        migrations.AddField(
            model_name='bonsortiedefinitiveg1',
            name='section',
            field=models.CharField(blank=True, max_length=100, verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='bonsortiedefinitiveg1',
            name='visa_controleur',
            field=models.CharField(blank=True, max_length=300, verbose_name='Visa du Contrôleur budgétaire ou du C.R.F.'),
        ),
        migrations.AddField(
            model_name='detailbonsortiedefinitiveg1',
            name='prix_conserver',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='P.U. à conserver'),
        ),
        migrations.AddField(
            model_name='detailbonsortiedefinitiveg1',
            name='prix_demolir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='P.U. à démolir'),
        ),
        migrations.AddField(
            model_name='detailbonsortiedefinitiveg1',
            name='prix_vendre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='P.U. à vendre'),
        ),
        migrations.AddField(
            model_name='detailbonsortiedefinitiveg1',
            name='qte_conserver',
            field=models.IntegerField(default=0, verbose_name='Qté à conserver ou à transformer'),
        ),
        migrations.AddField(
            model_name='detailbonsortiedefinitiveg1',
            name='qte_demolir',
            field=models.IntegerField(default=0, verbose_name='Qté à démolir'),
        ),
        migrations.AddField(
            model_name='detailbonsortiedefinitiveg1',
            name='qte_vendre',
            field=models.IntegerField(default=0, verbose_name='Qté à vendre'),
        ),
        migrations.AlterField(
            model_name='bonsortiedefinitiveg1',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Date du PV'),
        ),
        migrations.AlterField(
            model_name='bonsortiedefinitiveg1',
            name='num_bon',
            field=models.IntegerField(verbose_name='N° PV'),
        ),
    ]
