# Generated by Django 6.0.6 on 2026-07-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0014_sortie_def_g1_reforme_restructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailbonsortiedefinitiveg1',
            name='prix_conserver',
        ),
        migrations.RemoveField(
            model_name='detailbonsortiedefinitiveg1',
            name='prix_demolir',
        ),
        migrations.RemoveField(
            model_name='detailbonsortiedefinitiveg1',
            name='prix_vendre',
        ),
        migrations.RemoveField(
            model_name='detailbonsortiedefinitiveg1',
            name='qte_conserver',
        ),
        migrations.RemoveField(
            model_name='detailbonsortiedefinitiveg1',
            name='qte_demolir',
        ),
        migrations.RemoveField(
            model_name='detailbonsortiedefinitiveg1',
            name='qte_vendre',
        ),
        migrations.AddField(
            model_name='detailbonsortiedefinitiveg1',
            name='decision',
            field=models.CharField(choices=[('conserver', 'À conserver ou à transformer'), ('vendre', 'À vendre'), ('demolir', 'À démolir')], default='conserver', max_length=10, verbose_name='Décision de la commission'),
        ),
        migrations.AddField(
            model_name='detailbonsortiedefinitiveg1',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='P.U. réforme'),
        ),
        migrations.AddField(
            model_name='detailbonsortiedefinitiveg1',
            name='qte',
            field=models.IntegerField(default=0, verbose_name='Quantité'),
        ),
    ]
