# Generated by Django 6.0.6 on 2026-07-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0015_remove_detailbonsortiedefinitiveg1_prix_conserver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscompte',
            name='intitule_cb',
            field=models.CharField(blank=True, max_length=255, verbose_name='Intitulé CB'),
        ),
        migrations.AddField(
            model_name='souscompte',
            name='num_cb',
            field=models.CharField(blank=True, max_length=30, verbose_name='NumCB'),
        ),
    ]
