# Generated by Django 6.0.6 on 2026-07-27 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0016_souscompte_intitule_cb_souscompte_num_cb'),
    ]

    operations = [
        migrations.AddField(
            model_name='souscompte',
            name='compte',
            field=models.CharField(blank=True, max_length=20, verbose_name='Compte'),
        ),
    ]
