# Generated by Django 6.0.6 on 2026-08-13 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0017_souscompte_compte'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCommandeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bon', models.IntegerField(verbose_name='N° Bon')),
                ('date_creation', models.DateField(verbose_name='Date')),
                ('annee_exercice', models.IntegerField(blank=True, null=True, verbose_name='Année')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('envoye', 'Envoyé'), ('valide', 'Validé'), ('rejete', 'Rejeté')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('date_envoi', models.DateField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('date_validation', models.DateField(blank=True, null=True, verbose_name='Date de validation')),
                ('valide_par', models.CharField(blank=True, max_length=200, verbose_name='Validé par')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.bureau', verbose_name='Bureau')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Bon de commande de service',
                'verbose_name_plural': 'Bons de commande de services',
                'ordering': ['-date_creation', '-num_bon'],
            },
        ),
        migrations.AddField(
            model_name='bonsortiedefinitive',
            name='bon_commande_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_sortie', to='matieres.boncommandeservice', verbose_name='Bon de commande de service lié'),
        ),
        migrations.CreateModel(
            name='DetailBonCommandeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('nomenclature', models.CharField(blank=True, max_length=30, verbose_name='Nomenclature')),
                ('specification', models.CharField(blank=True, max_length=300, verbose_name='Spécification')),
                ('qte_commandee', models.IntegerField(default=0, verbose_name='Quantité commandée')),
                ('observation', models.CharField(blank=True, max_length=300, verbose_name='Observation')),
                ('bon_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='matieres.boncommandeservice')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.produit', verbose_name='Produit')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.unite', verbose_name='Unité')),
            ],
            options={
                'verbose_name': 'Détail bon de commande de service',
                'verbose_name_plural': 'Détails bons de commande de services',
            },
        ),
        migrations.AddField(
            model_name='detailbonsortiedefinitive',
            name='detail_commande_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons', to='matieres.detailboncommandeservice', verbose_name='Ligne de commande de service livrée'),
        ),
        migrations.CreateModel(
            name='ExpressionBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('date_creation', models.DateField(verbose_name='Date de création')),
                ('recu_par_comptable', models.BooleanField(default=False, verbose_name='Reçu par le comptable')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('recu', 'Reçu par comptable'), ('transforme', 'Transformé en BSD')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('date_reception_comptable', models.DateField(blank=True, null=True, verbose_name='Date de réception comptable')),
                ('bon_sortie_definitive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.bonsortiedefinitive', verbose_name='Bon de sortie définitive lié')),
                ('demandeur_bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.bureau', verbose_name='Bureau demandeur')),
                ('demandeur_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.service', verbose_name='Service demandeur')),
            ],
            options={
                'verbose_name': 'Expression de besoin',
                'verbose_name_plural': 'Expressions de besoins',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DetailExpressionBesoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('nomenclature', models.CharField(max_length=50, verbose_name='Nomenclature')),
                ('specification', models.CharField(blank=True, max_length=300, verbose_name='Spécification')),
                ('qte', models.IntegerField(default=0, verbose_name='Quantité')),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TTC')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.produit', verbose_name='Produit')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.unite', verbose_name='Unité')),
                ('expression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='matieres.expressionbesoin')),
            ],
            options={
                'verbose_name': 'Détail expression de besoin',
                'verbose_name_plural': 'Détails expressions de besoins',
            },
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_marche', models.CharField(max_length=100, unique=True, verbose_name='Numéro du marché')),
                ('date_creation', models.DateField(verbose_name='Date de création')),
                ('date_debut', models.DateField(blank=True, null=True, verbose_name='Date début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('num_bon_engagement', models.IntegerField(default=0, verbose_name="N° Bon d'engagement")),
                ('reference_marche', models.CharField(blank=True, max_length=200, verbose_name='Référence du marché')),
                ('chapitre', models.CharField(blank=True, max_length=100, verbose_name='Chapitre')),
                ('bon_entree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.bonentree', verbose_name="Bon d'entrée lié")),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Marché',
                'verbose_name_plural': 'Marchés',
                'ordering': ['-date_creation', 'num_marche'],
            },
        ),
        migrations.CreateModel(
            name='DetailMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=300, verbose_name='Désignation')),
                ('nomenclature', models.CharField(max_length=30, verbose_name='Nomenclature')),
                ('specification', models.CharField(blank=True, max_length=300, verbose_name='Spécification')),
                ('qte', models.IntegerField(default=0, verbose_name='Quantité')),
                ('prix_ht', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix HT')),
                ('prix_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Prix TTC')),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Montant TTC')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('produit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.produit', verbose_name='Produit')),
                ('unite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matieres.unite', verbose_name='Unité')),
                ('marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='matieres.marche')),
            ],
            options={
                'verbose_name': 'Détail du marché',
                'verbose_name_plural': 'Détails du marché',
            },
        ),
    ]
