# Generated by Django 6.0.6 on 2026-08-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0018_boncommandeservice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncommandeservice',
            name='demande_par',
            field=models.CharField(blank=True, max_length=200, verbose_name='Chef de Service (demandeur)'),
        ),
        migrations.AddField(
            model_name='boncommandeservice',
            name='destinataire',
            field=models.CharField(blank=True, max_length=200, verbose_name='À M. (destinataire)'),
        ),
        migrations.AlterField(
            model_name='boncommandeservice',
            name='valide_par',
            field=models.CharField(blank=True, max_length=200, verbose_name='Le S.A.F. (validé par)'),
        ),
    ]
