# Generated by Django 6.0.6 on 2026-08-28 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0020_profilutilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boncommandeservice',
            name='bureau',
        ),
        migrations.AddField(
            model_name='depot',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='depot',
            name='libelle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Libellé'),
        ),
        migrations.AddField(
            model_name='depot',
            name='responsable',
            field=models.CharField(blank=True, max_length=200, verbose_name='Comptable des matières (responsable)'),
        ),
        migrations.AlterField(
            model_name='boncommandeservice',
            name='destinataire',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='À M. (destinataire)'),
        ),
        migrations.RunSQL(
            "UPDATE matieres_boncommandeservice SET destinataire = NULL WHERE destinataire = ''",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='boncommandeservice',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_commande_service', to='matieres.depot', verbose_name='Destinataire (comptable des matières)'),
        ),
    ]
