# Generated by Django 6.0.6 on 2026-08-28 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0021_remove_boncommandeservice_bureau_depot_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilutilisateur',
            name='depot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils_comptables', to='matieres.depot', verbose_name='Dépôt rattaché (obligatoire pour un comptable des matières)'),
        ),
    ]
