# Generated by Django 6.0.6 on 2026-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0024_renommer_codes_depots_comptables'),
    ]

    operations = [
        migrations.AddField(
            model_name='depot',
            name='comptes_principaux',
            field=models.ManyToManyField(blank=True, related_name='depots', to='matieres.compteprincipale', verbose_name='Comptes principaux gérés par ce dépôt'),
        ),
        migrations.AddField(
            model_name='depot',
            name='sous_comptes_specifiques',
            field=models.ManyToManyField(blank=True, related_name='depots_specifiques', to='matieres.souscompte', verbose_name='Sous-comptes gérés en exception (prioritaires sur le compte principal)'),
        ),
    ]
