# Generated by Django 6.0.6 on 2026-08-31 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matieres', '0026_repartir_comptes_par_depot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marche',
            name='bon_entree',
        ),
        migrations.AddField(
            model_name='bonentree',
            name='marche',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_entree', to='matieres.marche', verbose_name='Marché lié'),
        ),
        migrations.AddField(
            model_name='marche',
            name='statut',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('solde', 'Soldé'), ('annule', 'Annulé')], default='en_cours', max_length=10, verbose_name='Statut'),
        ),
    ]
